build: off

notifications:
  - provider: Email
    on_build_success: false
    on_build_failure: true
    on_build_status_changed: false

environment:
    matrix:
      - PRJ_GEN: "Visual Studio 10 2010 Win64"
        BDIR: msvc2010
      - PRJ_GEN: "Visual Studio 11 2012 Win64"
        BDIR: msvc2012
      - PRJ_GEN: "Visual Studio 12 2013 Win64"
        BDIR: msvc2013
      - PRJ_GEN: "Visual Studio 14 2015 Win64"
        BDIR: msvc2015

build_script:
    - mkdir build.%BDIR% && cd build.%BDIR%
    - appveyor DownloadFile https://raw.githubusercontent.com/horta/zstd.install/master/install.bat && install.bat

test_script:
    - if NOT exist "%programfiles%\zstd\bin\zstd.dll" exit 1
    - if NOT exist "%programfiles%\zstd\lib\zstd.lib" exit 1
    - if NOT exist "%programfiles%\zstd\lib\zstd_static.lib" exit 1
    - if NOT exist "%programfiles%\zstd\include\zstd.h" exit 1
    - if NOT exist "%programfiles%\zstd\include\zstd_errors.h" exit 1
